services:
    mlflow:
        container_name: mlflow
        build: ./MLflow
        ports:
            - 5000:5000
        volumes:
          - ./prefect:/root/.prefect
        networks:
            - mlops
    
    api:
        container_name: api
        build: ./API
        ports:
            - 8080:8080
        networks:
            - mlops
        depends_on:
            - mlflow

networks:
    mlops:
        name: mlops
        driver: bridge
